version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Start prebuild and end it"
  build:
    commands:
      - echo "Running build"
      - commande_inexistante   # ❌ Cette commande n'existe pas, le build échouera
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - "**/*"
  base-directory: .
